# Generated by Django 6.0.2 on 2026-02-25 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_buddy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritevideo",
            name="video_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="favoritevideo",
            unique_together={("user", "video_id")},
        ),
    ]
