# Generated by Django 6.0.2 on 2026-02-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('gen_ai', 'Generative AI'), ('ml', 'Machine Learning'), ('prompt', 'Prompt Engineering'), ('llm', 'Large Language Models'), ('ethics', 'AI Ethics'), ('web_ai', 'AI in Web Development'), ('general', 'General AI')], default='general', max_length=20),
        ),
    ]
