# Generated by Django 6.0.2 on 2026-02-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('gen_ai', 'Generative AI'), ('ml', 'Machine Learning'), ('prompt', 'Prompt Engineering'), ('llm', 'Large Language Models'), ('ethics', 'AI Ethics'), ('web_ai', 'AI in Web Development'), ('general', 'General AI'), ('cloud', 'Cloud Computing'), ('devops', 'DevOps & Git'), ('cyber', 'Cyber Security'), ('data', 'Data Science'), ('mobile', 'Mobile Development'), ('blockchain', 'Web3 & Blockchain'), ('iot', 'Internet of Things'), ('hr', 'HR Interview Prep')], default='general', max_length=20),
        ),
    ]
