# Generated by Django 6.0.2 on 2026-02-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, help_text="Type your note here if you don't have a file."),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='study_notes/'),
        ),
    ]
