# Generated by Django 6.0.2 on 2026-02-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
