# Generated by Django 6.0.2 on 2026-02-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_userprogress_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='badges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
    ]
