# Generated by Django 6.0.2 on 2026-02-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_userprogress_badges_userprogress_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_playground_uses',
            field=models.IntegerField(default=0),
        ),
    ]
